### ISSUE TITLE
Missing pointers in the "fixup" file (US version)

### ISSUE THREAD

**Issue by Greengoblin007** [cebix/ff7tools#3]
Hi Christian,

I've been told that the chocobo racing minigame does not work properly in the US version, and that happens because there are some pointers or data missing in the "fixup" file. These are the correct values:

# Data files of the Chocobo Racing minigame, US version
patchChocoboUS = [
    ("MINI/CHOCOBO.BIN", [
        {
            "offset": 0x00002798,
            "check": 0x2404032c,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0099,
        },
        {
            "offset": 0x0000279c,
            "check": 0x240403c1,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x012e,
        },
        {
            "offset": 0x000027d4,
            "check": 0x240403f1,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x015e,
        },
        {
            "offset": 0x000027e4,
            "check": 0x240403ce,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x013b,
        },
        {
            "offset": 0x00002820,
            "check": 0x24040459,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x01c6,
        },
        {
            "offset": 0x0000283c,
            "check": 0x2404049c,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0209,
        },
        {
            "offset": 0x0000284c,
            "check": 0x24040433,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x01A0,
        },
        {
            "offset": 0x00002850,
            "check": 0x24040417,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0184,
        },
        {
            "offset": 0x00002888,
            "check": 0x2404033e,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x00AB,
        },
        {
            "offset": 0x00002898,
            "check": 0x24040293,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0000,
        },
        {
            "offset": 0x000028e0,
            "check": 0x240404c9,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0236,
        },
        {
            "offset": 0x00002904,
            "check": 0x240404ca,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0237,
        },
        {
            "offset": 0x00002928,
            "check": 0x240404c8,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0235,
        },
        {
            "offset": 0x0000294c,
            "check": 0x240404c7,
            "coderef": 'MINI/CHOCOBO.DAT',
            "startblock": 0x0234,
        },
    ]),
]

Here I attach the corrected file: [fixup.zip](https://github.com/user-attachments/files/16635482/fixup.zip)

Regards

**Comment by cebix** [comment]
Nice find, thanks!
